package com.fashionworld.backend.model;

import java.util.Date;
import java.util.List;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "orders")
public class Order {

    @Id
    private String id;
    
    // Original Order ID generated by frontend (e.g., ORD-XXXXXXXXX)
    private String orderId; 

    private String userId;
    
    private List<OrderItem> items;
    
    private Address shippingAddress; // Now using the unified Address class
    
    private double totalAmount;
    
    private String paymentMethod; // e.g., "Cash on Delivery"
    
    private String status; // e.g., "Processing", "Shipped", "Delivered", "Cancelled"
    
    private int trackingStep; // e.g., 2 (Processing), 3 (Shipped), etc.

    @CreatedDate
    private Date createdAt;
}
