package com.fashionworld.backend.model;

import java.util.Date;
import java.util.List;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "orders")
public class Order {

    @Id
    private String id;
    
    // Original Order ID generated by frontend (e.g., ORD-XXXXXXXXX)
    private String orderId; 

    private String userId; // Optional for offline orders
    
    // Offline / In-Store Fields
    @JsonProperty("isOffline")
    private boolean isOffline; // True if sold in-shop, False if online
    private String staffId; // ID of the staff who processed the sale
    private String customerName; // Direct name for offline customers
    private String customerPhone; // Required for offline lookup
    private String customerEmail; // Optional for offline
    
    // Financial Details (POS Specific)
    private double subTotal;
    private double tax;
    private double discount;
    private double cashReceived; // Amount handed by customer
    private double balanceReturned; // Change given back
    
    private List<OrderItem> items;
    
    private Address shippingAddress; // Now using the unified Address class (Optional for offline)
    
    private double totalAmount;
    
    private String paymentMethod; // e.g., "Cash on Delivery", "Cash", "Card"
    
    private String status; // e.g., "Processing", "Shipped", "Delivered", "Cancelled", "Completed"
    
    private int trackingStep; // e.g., 2 (Processing), 3 (Shipped), etc.
    
    private List<StatusUpdate> statusHistory;

    @CreatedDate
    private Date createdAt;
}
